export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FALIURE = 'LOGIN_FALIURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FALIURE = 'LOGOUT_FALIURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FALIURE = 'SIGNUP_FALIURE';

export const GET_CAT_REQUEST = 'GET_CAT_REQUEST';
export const GET_CAT_SUCCESS = 'GET_CAT_SUCCESS';
export const GET_CAT_FALIURE = 'GET_CAT_FALIURE';

export const GET_PRO_REQUEST = 'GET_PRO_REQUEST';
export const GET_PRO_SUCCESS = 'GET_PRO_SUCCESS';
export const GET_PRO_FALIURE = 'GET_CAT_FALIURE';

export const ADD_NEW_CAT_REQUEST = 'ADD_NEW_CAT_REQUEST';
export const ADD_NEW_CAT_SUCCESS = 'ADD_NEW_CAT_SUCCESS';
export const ADD_NEW_CAT_FALIURE = 'ADD_NEW_CAT_FALIURE';

export const ADD_NEW_PRO_REQUEST = 'ADD_NEW_PRO_REQUEST';
export const ADD_NEW_PRO_SUCCESS = 'ADD_NEW_PRO_SUCCESS';
export const ADD_NEW_PRO_FALIURE = 'ADD_NEW_PRO_FALIURE';

export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FALIURE = 'GET_DATA_FALIURE';